[package]
name = "podzol"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = [
    "derive",
    "cargo",
    "env",
    "unicode",
    "wrap_help",
] }
reqwest = { version = "0.12.12", features = [
    "gzip",
    "brotli",
    "zstd",
    "deflate",
    "json",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serde_with = { version = "3.12.0", default-features = false, features = ["macros"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
toml_edit = { version = "0.22.22", features = ["serde"] }
