[package]
name = "podzol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive", "cargo", "env", "unicode", "wrap_help"] }
serde = { version = "1.0.217", features = ["derive"] }
toml_edit = { version = "0.22.22", features = ["serde"] }
